# ROM-agnostic MiuiCit integration.
MIUICIT_PATH := $(call my-dir)

PRODUCT_SOONG_NAMESPACES += \
    $(MIUICIT_PATH)

PRODUCT_PACKAGES += \
    MiuiCit \
    miuicit_mondrian_config \
    miuicit_hardware_init

# Optional factory runtime generated by tools/import-stock-runtime.sh.
ifneq ($(wildcard $(MIUICIT_PATH)/runtime/generated/generated-runtime.mk),)
include $(MIUICIT_PATH)/runtime/generated/generated-runtime.mk
endif
